#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("minrva.Droid.Resource", IsApplication=true)]

namespace minrva.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::minrva.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Gem1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Gem3 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Gem5 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Gem6 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Gem8 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Gem9 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int gender_neutral_user = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int minrva_icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int minrva_icon_100px = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Rock = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout_rating = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int file_paths = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
